import { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import fs from 'fs';
import matter from 'gray-matter';

import { Article } from '@/types/Article';
import { Header } from '@/components/Header';
import { ArticleIndex } from '@/components/ArticleIndex';

type IndexPageProps = {
  articles: Article[];
};

const IndexPage: NextPage<IndexPageProps> = ({ articles }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <Header isTopPage={true} />
        <ArticleIndex articles={articles} />
      </div>
    </>
  );
};

export const getStaticProps: GetStaticProps<IndexPageProps> = async () => {
  const articles: Article[] = [];

  try {
    const dirents = await fs.promises.readdir('./articles/', {
      withFileTypes: true,
    });

    const sortedFiles = dirents
      .map((dirent) => {
        return dirent.name;
      })
      .sort()
      .reverse();

    sortedFiles.forEach((fileName) => {
      const date = fileName.match(/^\d{4}-\d{2}-\d{2}/)?.[0];

      if (date) {
        const fileContents = fs.readFileSync(`./articles/${fileName}`, 'utf-8');
        const articleData = matter(fileContents);

        articles.push({
          slug: fileName.replace('.md', ''),
          date,
          title: articleData.data.title,
        });
      }
    });
  } catch (error) {
    console.log(error);
  }

  return {
    props: {
      articles,
    },
  };
};

export default IndexPage;
