import fs from 'fs';
import matter from 'gray-matter';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import { ReactElement } from 'react';

import { ArticleIndex } from '@/components/ArticleIndex';
import Layout from '@/components/Layout';
import { NextPageWithLayout } from '@/pages/_app';
import { Article } from '@/types/Article';

type IndexPageProps = {
  articles: Article[];
};

const IndexPage: NextPageWithLayout<IndexPageProps> = ({ articles }) => {
  return (
    <>
      <Head>
        <title>taqun.me</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ArticleIndex articles={articles} />
    </>
  );
};

IndexPage.getLayout = (page: ReactElement) => {
  return <Layout isTopPage>{page}</Layout>;
};

export const getStaticProps: GetStaticProps<IndexPageProps> = async () => {
  const articles: Article[] = [];

  try {
    const dirents = await fs.promises.readdir('./articles/', {
      withFileTypes: true,
    });

    const sortedFiles = dirents
      .map((dirent) => {
        return dirent.name;
      })
      .sort()
      .reverse();

    sortedFiles.forEach((fileName) => {
      const date = fileName.match(/^\d{4}-\d{2}-\d{2}/)?.[0];

      if (date) {
        const fileContents = fs.readFileSync(`./articles/${fileName}`, 'utf-8');
        const articleData = matter(fileContents);

        articles.push({
          slug: fileName.replace('.md', ''),
          date,
          title: articleData.data.title,
        });
      }
    });
  } catch (error) {
    console.log(error);
  }

  return {
    props: {
      articles,
    },
  };
};

export default IndexPage;
