import Head from 'next/head';
import { FC, ReactElement } from 'react';

import { Header } from '@/components/Header';

type LayoutProps = {
  isTopPage?: boolean;
  children: ReactElement;
};

const Layout: FC<LayoutProps> = ({ isTopPage, children }) => {
  return (
    <>
      <Head>
        <title>taqun.me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="container">
        <Header isTopPage={isTopPage} />
        {children}
      </div>
    </>
  );
};

export default Layout;
