name: import

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      OUT_DIR: './articles'
      IMAGE_DIR: './public'
    steps:
      - uses: actions/checkout@v3
      - uses: taqun/notion-to-markdown@main
      - id: check-diff
        run: |
          git add -N .
          git diff --exit-code
        continue-on-error: true
      - run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m 'Import'
          git push
        if: steps.check-diff.outcome == 'failure'