name: test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      OUT_DIR: './articles'
      IMAGE_DIR: './public'
    steps:
      - uses: taqun/notion-to-markdown@main
